#!/bin/bash

remote="$1"

if [ -z "$remote" ]; then
	remote="ariane"
fi

function on_exit() # Called by trap
{
	exit 0
}

trap on_exit INT

# Initial sync
if [ "$remote" != "localhost" ]; then
	rsync -v --exclude=mixtures_dat.dat "${remote}:libstable/mixture*" . > /dev/null
fi

nlines=$(wc -l < mixtures_rnd.dat | sed -E 's/[[:space:]]+//g')

if [ -z "$2" ]; then
	margin=$((5 * nlines / 200))
else
	margin="$2"
fi

echo "$nlines samples, margin is $margin"

minx=$(head -n $margin mixtures_rnd.dat | tail -n 1)
maxx=$(tail -n $margin mixtures_rnd.dat | head -n 1)

echo "Data range is $minx $maxx"

gnuplot gnuplot/mixture.gp &

while true ; do
	if [ "$remote" != "localhost" ]; then
		rsync --exclude=mixtures_dat.dat "${remote}:libstable/mixture*" . > /dev/null
	fi

	tail -n 1  mixture_debug.dat | awk '{ $1 = ""; $2 = ""; print }' | \
		xargs -s $(getconf ARG_MAX) bin/release/stable_plot_mixture $minx $maxx > tmp_result.dat

	if [ $(wc -l tmp_result.dat | awk '{print $1}') -ge 10 ]; then
		cp tmp_result.dat mixtures_dat.dat
	fi

	sleep 1
done
