#!/bin/bash

tbold=$(tput bold)
treset=$(tput sgr0)
tred=$(tput setaf 1)
tgreen=$(tput setaf 2)
tyellow=$(tput setaf 3)
host=gjulian@azufre.ii.uam.es
path=/home/gjulian/libstable

if [ ! -z "$1" ]; then
	host=$1
fi

if [ ! -z "$2" ]; then
	path=$2
fi

function echob()
{
	echo ${tbold}$@${treset}
}

function remote_make()
{
	path=$1
	name=$2

	out=$(ssh -t $host "cd $path; make -j 8" 2>&1)
	retval=$?
	echo "$out" | ./hilite.sh -f red [Ee]rror | ./hilite.sh -f yellow warning

	if [ $retval -ne 0 ]; then
		echob ${tred}Compilation failed.
		exit 1
	fi

	echob ${tgreen}$name is compiling at $(date)
}

echo "Target: $host"
echob "Syncing files..."
rsync -avzPt --exclude=.git --exclude=data --exclude=results \
	--exclude=obj --exclude=bin --exclude=lib --exclude="*pdf" \
	--exclude="*.dat" --exclude="*.results" --exclude="*.txt" \
	--exclude="*.out" \
	-- ./ $host:$path || (echo ${tred}Sync failed.${tnorm} && exit 1)
echob "Synced. Remoting to compile..."

remote_make $path Library
