#!/bin/bash

tbold=$(tput bold)
treset=$(tput sgr0)
tred=$(tput setaf 1)
tgreen=$(tput setaf 2)
tyellow=$(tput setaf 3)
host=gjulian@azufre.ii.uam.es

function echob()
{
	echo ${tbold}$@${treset}
}

function remote_make()
{
	path=$1
	name=$2

	out=$(ssh -t $host "cd $path; make all" 2>&1)
	retval=$?
	echo "$out" | ./hilite.sh -f red [Ee]rror | ./hilite.sh -f yellow warning

	if [ $retval -ne 0 ]; then
		echob ${tred}Compilation failed.
		exit 1
	fi

	echob ${tgreen}$name is compiling.
}

function remote_exec()
{
	path=$1
	cmd=$2

	out=$(ssh -t $host "cd $path; $cmd" 2>&1)
	retval=$?

	if [ $retval -ne 0 ]; then
		echob ${tred}Execution failed.
		exit 1
	fi

	echob ${tgreen}Command \"$cmd\" executed.
}

echob "Syncing files..."
rsync -avzPt --exclude=.git --exclude=data --exclude=results ./ $host:/home/gjulian/libstable || (echo ${tred}Sync failed.${tnorm} && exit 1)
echob "Synced. Remoting to compile..."

remote_make /home/gjulian/libstable Library
remote_exec /home/gjulian/libstable "bin/debug/gpu_performance | tail -n +2 > gpu_perf_results"
./copy_results
