#!/bin/bash

input_folder="$1"
ls_target="$1"
output_folder="results/mixtures"

function on_exit() # Called by trap
{
	exit 0
}

trap on_exit INT

if [ -z "$1" ]; then
	echo "usage: batch_mixture_estimation [input folder]"
	exit 1
fi

if [ -f "$input_folder" ]; then
	input_folder="$(dirname $input_folder)"
fi

mkdir -p $output_folder

for f in $(ls $ls_target); do
	f="$(basename $f)"
	echo "Estimation for $f..."
	bin/release/mixtures "$input_folder/$f" > "$output_folder/$f.txt"
	echo "- Plotting histogram"
	gnuplot -e "outfile='$output_folder/$f-hist.png'" gnuplot/histogram.gp
	echo "- Plotting ECDF"
	gnuplot -e "outfile='$output_folder/$f-ecdf.png'" gnuplot/ecdf.gp
	echo "- Plotting MonteCarlo evolution"
	gnuplot -e "outfile='$output_folder/$f-evolution.png'" gnuplot/mixture.gp
done
