#!/bin/bash

# Set the correct CWD
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

cd "$DIR"/..

function finish {
  	git checkout -- .
	if [ $dirty -ne 0 ]; then
		git undo-commit
	fi
}

trap finish EXIT

# Save the current state of the codebase if necessary
git diff --exit-code --quiet
dirty=$?


if [ $dirty -ne 0 ]; then
	git add -A
	git commit -m "Temporal savepoint"
fi

# Apply the patch for dirty logging
patch -p1 < scripts/loglikelihoodgraph.patch

# Build
make release

# Execute the fit test
bin/release/fittest

# Plot it
gnuplot gnuplot/loglikelihoodgraph.gp

# Undo the changes
